### ISSUE TITLE
Not able to set POI for features available on map and displaying as label using Identify functionality.

### ISSUE THREAD

**Issue by ShomeTester** [DoITRaj/DoIT-Citizen#25]
1. Zoom map to the level where labels are available e.g Panchsheel Colony.
2. Click on map.

Result : Panchsheel Colony is not auto populating in Search POI, lefet panel.

Please check

**Comment by ArchanaSingh2305** [comment]
@sksaurav03 Please check and fix the issue.

**Comment by ArchanaSingh2305** [comment]
@ShomeTester @AchanaJoshi The data that we are referring to here is actually point data with long labels. Since the customers don't want the points to be visible, only the labels have been shown on the map. Therefore while clicking on the label sometimes the feature is not identified. The tiling is already going on and  changing the symbology at this point will lead to doing it all over again, which will be very time consuming. This will be catered layer with next level of basemap changes.

**Comment by AchanaJoshi** [comment]
@ArchanaSingh2305 @ShomeTester 
Discussed with Shome. He is agreed to close it based on developer comments
